#!/bin/sh
export SIREUM_DIST=true
export SIREUM_HOME=`dirname $(cd "${0%/*}" 2>/dev/null; echo "$PWD"/"${0##*/}")`
if [ $0 -nt $0.jar ]
  then
    echo "Please wait while Sireum is loading..."
    echo
fi
exec scala -nocompdaemon -savecompiled $SCALA_OPTIONS $0 $SIREUM_HOME $@
!#
SireumDistro.main(argv)
