#!/bin/bash
export SIREUM_DIST=true
export SIREUM_HOME=`dirname $(cd "${0%/*}" 2>/dev/null; echo "$PWD"/"${0##*/}")`
if [ -f $0.jar ]; then
  if [ $0 -nt $0.jar ]; then
    echo "Please wait while Sireum is loading..."
    echo
  fi
else
  echo "Please wait while Sireum is loading..."
  echo
fi
if [ -d $SIREUM_HOME/apps/platform/java ]; then
  export JAVA_HOME=$SIREUM_HOME/apps/platform/java
  export PATH=$JAVA_HOME/bin:$PATH
fi
if [ -d $SIREUM_HOME/apps/platform/scala ]; then
  export SCALA_HOME=$SIREUM_HOME/apps/platform/scala
  export PATH=$SCALA_HOME/bin:$PATH
fi
${SCALA_BIN:=scala} -target:jvm-1.7 -language:reflectiveCalls -nocompdaemon -savecompiled $SCALA_OPTIONS $0 $SIREUM_HOME "$@"
code=$?
if [ -d $JAVA_HOME.new ]; then
  rm -fR $JAVA_HOME
  mv $JAVA_HOME.new $JAVA_HOME
fi
if [ -d $SCALA_HOME.new ]; then
  rm -fR $SCALA_HOME
  mv $SCALA_HOME.new $SCALA_HOME
fi
if [ -f $0.new ]; then
  mv -f $0.new $0
  chmod +x $0
  echo "Reloading Sireum..."
  echo
  exec $0 update
fi
exit $code 
!#
SireumDistro.main(argv)
