#!/bin/bash
export SIREUM_DIST=true
export SIREUM_HOME=$( cd "$( dirname "$0" )" &> /dev/null && pwd )
if [ -f $0.jar ]; then
  if [ $0 -nt $0.jar ]; then
    echo "Please wait while Sireum is loading..."
    echo
  fi
else
  echo "Please wait while Sireum is loading..."
  echo
fi
if [ -d $SIREUM_HOME/apps/platform/java ]; then
  export JAVA_HOME=$SIREUM_HOME/apps/platform/java
  export PATH=$JAVA_HOME/bin:$PATH
fi
if [ -d $SIREUM_HOME/apps/platform/scala ]; then
  export SCALA_HOME=$SIREUM_HOME/apps/platform/scala
  export PATH=$SCALA_HOME/bin:$PATH
fi
${SCALA_BIN:=scala} -target:jvm-1.7 -nocompdaemon -savecompiled $SCALA_OPTIONS $0 $SIREUM_HOME "$@"
code=$?
if [ -d $SIREUM_HOME/apps/platform/java.new ]; then
  rm -fR $SIREUM_HOME/apps/platform/java
  mv $SIREUM_HOME/apps/platform/java.new $SIREUM_HOME/apps/platform/java
  rm -f $0.jar
  export RELOAD=true
fi
if [ -d $SIREUM_HOME/apps/platform/scala.new ]; then
  rm -fR $SIREUM_HOME/apps/platform/scala
  mv $SIREUM_HOME/apps/platform/scala.new $SIREUM_HOME/apps/platform/scala
  rm -f $0.jar
  export RELOAD=true
fi
if [ -f $0.new ]; then
  export RELOAD=true
fi
if [ ! -z "$RELOAD" ]; then 
  mv -f $0.new $0
  chmod +x $0
  echo "Reloading Sireum..."
  echo
  exec "$0" "$@"
fi
exit $code 
!#
SireumDistro.main(argv)
