//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.06 at 08:46:22 AM CST 
//


package org.sireum.bakar.gnatxml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Expression_List complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Expression_List">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="not_an_element" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="discrete_range_attribute_reference" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="discrete_simple_expression_range" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="others_choice" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="box_expression" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="integer_literal" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="real_literal" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="string_literal" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="identifier" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="and_operator" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="or_operator" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="xor_operator" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="equal_operator" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="not_equal_operator" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="less_than_operator" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="less_than_or_equal_operator" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="greater_than_operator" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="greater_than_or_equal_operator" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="plus_operator" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="minus_operator" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="concatenate_operator" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="unary_plus_operator" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="unary_minus_operator" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="multiply_operator" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="divide_operator" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="mod_operator" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="rem_operator" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="exponentiate_operator" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="abs_operator" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="not_operator" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="character_literal" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="enumeration_literal" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="explicit_dereference" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="function_call" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="indexed_component" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="slice" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="selected_component" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="access_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="address_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="adjacent_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="aft_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="alignment_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="base_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="bit_order_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="body_version_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="callable_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="caller_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="ceiling_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="class_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="component_size_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="compose_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="constrained_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="copy_sign_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="count_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="definite_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="delta_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="denorm_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="digits_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="exponent_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="external_tag_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="first_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="first_bit_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="floor_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="fore_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="fraction_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="identity_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="image_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="input_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="last_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="last_bit_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="leading_part_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="length_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="machine_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="machine_emax_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="machine_emin_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="machine_mantissa_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="machine_overflows_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="machine_radix_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="machine_rounds_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="max_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="max_size_in_storage_elements_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="min_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="model_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="model_emin_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="model_epsilon_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="model_mantissa_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="model_small_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="modulus_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="output_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="partition_id_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="pos_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="position_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="pred_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="range_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="read_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="remainder_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="round_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="rounding_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="safe_first_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="safe_last_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="scale_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="scaling_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="signed_zeros_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="size_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="small_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="storage_pool_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="storage_size_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="succ_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="tag_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="terminated_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="truncation_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="unbiased_rounding_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="unchecked_access_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="val_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="valid_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="value_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="version_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="wide_image_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="wide_value_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="wide_width_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="width_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="write_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="machine_rounding_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="mod_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="priority_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="stream_size_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="wide_wide_image_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="wide_wide_value_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="wide_wide_width_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="max_alignment_for_allocation_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="overlaps_storage_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="implementation_defined_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="unknown_attribute" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="record_aggregate" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="extension_aggregate" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="positional_array_aggregate" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="named_array_aggregate" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="and_then_short_circuit" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="or_else_short_circuit" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="in_membership_test" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="not_in_membership_test" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="null_literal" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="parenthesized_expression" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="type_conversion" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="qualified_expression" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="allocation_from_subtype" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="allocation_from_qualified_expression" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="case_expression" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="if_expression" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="for_all_quantified_expression" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="for_some_quantified_expression" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;group ref="{}pragmas_group"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Expression_List", propOrder = {
    "notAnElementOrDiscreteRangeAttributeReferenceOrDiscreteSimpleExpressionRange"
})
public class ExpressionList {

    @XmlElementRefs({
        @XmlElementRef(name = "allocation_from_qualified_expression", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "null_literal", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "mod_operator", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "mod_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "machine_radix_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "not_equal_operator", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "pos_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "asynchronous_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "task_dispatching_policy_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "machine_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "independent_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "profile_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "size_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "interrupt_handler_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "exponentiate_operator", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "aft_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "export_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "range_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "denorm_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "slice", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "list_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "qualified_expression", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "version_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "safe_first_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ceiling_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "round_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "last_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "parenthesized_expression", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "machine_emax_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "priority_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "type_conversion", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "locking_policy_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "inline_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "multiply_operator", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "unary_minus_operator", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "storage_pool_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "or_else_short_circuit", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "atomic_components_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "priority_specific_dispatching_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "attach_handler_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "unchecked_union_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "string_literal", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "digits_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "model_mantissa_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "interrupt_priority_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "page_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "selected_component", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "remote_types_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "model_emin_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "implementation_defined_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "detect_blocking_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "optimize_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "and_then_short_circuit", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "wide_value_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "floor_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "first_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "component_size_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "wide_wide_width_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "integer_literal", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "dispatching_domain_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "not_operator", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "linker_options_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "value_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "pack_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "assert_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "inspection_point_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "max_size_in_storage_elements_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "function_call", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "scaling_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "fore_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "concatenate_operator", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "scale_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "rem_operator", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "in_membership_test", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "real_literal", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "shared_passive_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "box_expression", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "delta_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "case_expression", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "unknown_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "default_storage_pool_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "base_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "reviewable_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "storage_size_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "unsuppress_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "exponent_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "convention_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "succ_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "constrained_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "extension_aggregate", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "copy_sign_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "implementation_defined_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "stream_size_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "length_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "character_literal", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "if_expression", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "all_calls_remote_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "less_than_or_equal_operator", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "external_tag_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "wide_image_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "machine_mantissa_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "pred_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "bit_order_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "plus_operator", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "unary_plus_operator", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "unbiased_rounding_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "allocation_from_subtype", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "alignment_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "input_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "rounding_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "valid_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "terminated_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "fraction_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "wide_wide_value_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "priority_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "preelaborable_initialization_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "width_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "machine_emin_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "adjacent_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "pure_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "machine_rounds_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "unchecked_access_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "read_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "normalize_scalars_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "remote_call_interface_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "minus_operator", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "body_version_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "machine_overflows_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "signed_zeros_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "xor_operator", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "greater_than_or_equal_operator", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "discard_names_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "for_all_quantified_expression", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "compose_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "truncation_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "not_in_membership_test", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "small_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "volatile_components_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "model_epsilon_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "independent_components_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "others_choice", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "output_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "enumeration_literal", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "not_an_element", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "safe_last_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "partition_elaboration_policy_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "elaborate_body_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "position_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "model_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "assertion_policy_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "import_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "equal_operator", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "discrete_simple_expression_range", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "divide_operator", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "machine_rounding_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "preelaborate_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "for_some_quantified_expression", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "tag_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "write_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "volatile_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "definite_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "less_than_operator", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "partition_id_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "no_return_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "access_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "image_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "max_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "wide_width_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "indexed_component", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "wide_wide_image_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "address_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "modulus_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "queuing_policy_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "unknown_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "and_operator", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "positional_array_aggregate", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "relative_deadline_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "suppress_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "last_bit_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "count_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "identity_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "discrete_range_attribute_reference", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "or_operator", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "elaborate_all_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "leading_part_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "storage_size_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "cpu_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "identifier", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "restrictions_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "val_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "class_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "overlaps_storage_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "max_alignment_for_allocation_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "min_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "first_bit_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "elaborate_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "abs_operator", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "explicit_dereference", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "model_small_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "atomic_pragma", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "remainder_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "record_aggregate", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "callable_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "greater_than_operator", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "named_array_aggregate", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "caller_attribute", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "controlled_pragma", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<Object>> notAnElementOrDiscreteRangeAttributeReferenceOrDiscreteSimpleExpressionRange;

    /**
     * Gets the value of the notAnElementOrDiscreteRangeAttributeReferenceOrDiscreteSimpleExpressionRange property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the notAnElementOrDiscreteRangeAttributeReferenceOrDiscreteSimpleExpressionRange property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNotAnElementOrDiscreteRangeAttributeReferenceOrDiscreteSimpleExpressionRange().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * 
     */
    public List<JAXBElement<Object>> getNotAnElementOrDiscreteRangeAttributeReferenceOrDiscreteSimpleExpressionRange() {
        if (notAnElementOrDiscreteRangeAttributeReferenceOrDiscreteSimpleExpressionRange == null) {
            notAnElementOrDiscreteRangeAttributeReferenceOrDiscreteSimpleExpressionRange = new ArrayList<JAXBElement<Object>>();
        }
        return this.notAnElementOrDiscreteRangeAttributeReferenceOrDiscreteSimpleExpressionRange;
    }

}
