//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//

package org.sireum.bakar.gnatxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Generalized_Iterator_Specification complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Generalized_Iterator_Specification">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sloc" type="{}Source_Location"/>
 *         &lt;element name="names_ql" type="{}Defining_Name_List"/>
 *         &lt;element name="has_reverse_q">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="reverse" type="{}Reverse"/>
 *                   &lt;element name="not_an_element" type="{}Not_An_Element"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="iteration_scheme_name_q" type="{}Element_Class"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Generalized_Iterator_Specification", propOrder = { "sloc",
    "namesQl", "hasReverseQ", "iterationSchemeNameQ" })
public class GeneralizedIteratorSpecification {

  /**
   * <p>
   * Java class for anonymous complex type.
   * 
   * <p>
   * The following schema fragment specifies the expected content contained
   * within this class.
   * 
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;choice>
   *         &lt;element name="reverse" type="{}Reverse"/>
   *         &lt;element name="not_an_element" type="{}Not_An_Element"/>
   *       &lt;/choice>
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = { "reverse", "notAnElement" })
  public static class HasReverseQ {

    protected Reverse reverse;
    @XmlElement(name = "not_an_element")
    protected NotAnElement notAnElement;

    /**
     * Gets the value of the notAnElement property.
     * 
     * @return possible object is {@link NotAnElement }
     * 
     */
    public NotAnElement getNotAnElement() {
      return this.notAnElement;
    }

    /**
     * Gets the value of the reverse property.
     * 
     * @return possible object is {@link Reverse }
     * 
     */
    public Reverse getReverse() {
      return this.reverse;
    }

    /**
     * Sets the value of the notAnElement property.
     * 
     * @param value
     *          allowed object is {@link NotAnElement }
     * 
     */
    public void setNotAnElement(final NotAnElement value) {
      this.notAnElement = value;
    }

    /**
     * Sets the value of the reverse property.
     * 
     * @param value
     *          allowed object is {@link Reverse }
     * 
     */
    public void setReverse(final Reverse value) {
      this.reverse = value;
    }

  }

  @XmlElement(required = true)
  protected SourceLocation sloc;
  @XmlElement(name = "names_ql", required = true)
  protected DefiningNameList namesQl;
  @XmlElement(name = "has_reverse_q", required = true)
  protected GeneralizedIteratorSpecification.HasReverseQ hasReverseQ;

  @XmlElement(name = "iteration_scheme_name_q", required = true)
  protected ElementClass iterationSchemeNameQ;

  /**
   * Gets the value of the hasReverseQ property.
   * 
   * @return possible object is
   *         {@link GeneralizedIteratorSpecification.HasReverseQ }
   * 
   */
  public GeneralizedIteratorSpecification.HasReverseQ getHasReverseQ() {
    return this.hasReverseQ;
  }

  /**
   * Gets the value of the iterationSchemeNameQ property.
   * 
   * @return possible object is {@link ElementClass }
   * 
   */
  public ElementClass getIterationSchemeNameQ() {
    return this.iterationSchemeNameQ;
  }

  /**
   * Gets the value of the namesQl property.
   * 
   * @return possible object is {@link DefiningNameList }
   * 
   */
  public DefiningNameList getNamesQl() {
    return this.namesQl;
  }

  /**
   * Gets the value of the sloc property.
   * 
   * @return possible object is {@link SourceLocation }
   * 
   */
  public SourceLocation getSloc() {
    return this.sloc;
  }

  /**
   * Sets the value of the hasReverseQ property.
   * 
   * @param value
   *          allowed object is
   *          {@link GeneralizedIteratorSpecification.HasReverseQ }
   * 
   */
  public void setHasReverseQ(
      final GeneralizedIteratorSpecification.HasReverseQ value) {
    this.hasReverseQ = value;
  }

  /**
   * Sets the value of the iterationSchemeNameQ property.
   * 
   * @param value
   *          allowed object is {@link ElementClass }
   * 
   */
  public void setIterationSchemeNameQ(final ElementClass value) {
    this.iterationSchemeNameQ = value;
  }

  /**
   * Sets the value of the namesQl property.
   * 
   * @param value
   *          allowed object is {@link DefiningNameList }
   * 
   */
  public void setNamesQl(final DefiningNameList value) {
    this.namesQl = value;
  }

  /**
   * Sets the value of the sloc property.
   * 
   * @param value
   *          allowed object is {@link SourceLocation }
   * 
   */
  public void setSloc(final SourceLocation value) {
    this.sloc = value;
  }

}
