//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.06 at 08:46:22 AM CST 
//


package org.sireum.bakar.gnatxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Path_Class complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Path_Class">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="not_an_element" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="if_path" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="elsif_path" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="else_path" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="case_path" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="select_path" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="or_path" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="then_abort_path" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="case_expression_path" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="if_expression_path" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="elsif_expression_path" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="else_expression_path" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;group ref="{}pragmas_group"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Path_Class", propOrder = {
    "notAnElement",
    "ifPath",
    "elsifPath",
    "elsePath",
    "casePath",
    "selectPath",
    "orPath",
    "thenAbortPath",
    "caseExpressionPath",
    "ifExpressionPath",
    "elsifExpressionPath",
    "elseExpressionPath",
    "allCallsRemotePragma",
    "asynchronousPragma",
    "atomicPragma",
    "atomicComponentsPragma",
    "attachHandlerPragma",
    "controlledPragma",
    "conventionPragma",
    "discardNamesPragma",
    "elaboratePragma",
    "elaborateAllPragma",
    "elaborateBodyPragma",
    "exportPragma",
    "importPragma",
    "inlinePragma",
    "inspectionPointPragma",
    "interruptHandlerPragma",
    "interruptPriorityPragma",
    "linkerOptionsPragma",
    "listPragma",
    "lockingPolicyPragma",
    "normalizeScalarsPragma",
    "optimizePragma",
    "packPragma",
    "pagePragma",
    "preelaboratePragma",
    "priorityPragma",
    "purePragma",
    "queuingPolicyPragma",
    "remoteCallInterfacePragma",
    "remoteTypesPragma",
    "restrictionsPragma",
    "reviewablePragma",
    "sharedPassivePragma",
    "storageSizePragma",
    "suppressPragma",
    "taskDispatchingPolicyPragma",
    "volatilePragma",
    "volatileComponentsPragma",
    "assertPragma",
    "assertionPolicyPragma",
    "detectBlockingPragma",
    "noReturnPragma",
    "partitionElaborationPolicyPragma",
    "preelaborableInitializationPragma",
    "prioritySpecificDispatchingPragma",
    "profilePragma",
    "relativeDeadlinePragma",
    "uncheckedUnionPragma",
    "unsuppressPragma",
    "defaultStoragePoolPragma",
    "dispatchingDomainPragma",
    "cpuPragma",
    "independentPragma",
    "independentComponentsPragma",
    "implementationDefinedPragma",
    "unknownPragma"
})
public class PathClass {

    @XmlElement(name = "not_an_element")
    protected Object notAnElement;
    @XmlElement(name = "if_path")
    protected Object ifPath;
    @XmlElement(name = "elsif_path")
    protected Object elsifPath;
    @XmlElement(name = "else_path")
    protected Object elsePath;
    @XmlElement(name = "case_path")
    protected Object casePath;
    @XmlElement(name = "select_path")
    protected Object selectPath;
    @XmlElement(name = "or_path")
    protected Object orPath;
    @XmlElement(name = "then_abort_path")
    protected Object thenAbortPath;
    @XmlElement(name = "case_expression_path")
    protected Object caseExpressionPath;
    @XmlElement(name = "if_expression_path")
    protected Object ifExpressionPath;
    @XmlElement(name = "elsif_expression_path")
    protected Object elsifExpressionPath;
    @XmlElement(name = "else_expression_path")
    protected Object elseExpressionPath;
    @XmlElement(name = "all_calls_remote_pragma")
    protected Object allCallsRemotePragma;
    @XmlElement(name = "asynchronous_pragma")
    protected Object asynchronousPragma;
    @XmlElement(name = "atomic_pragma")
    protected Object atomicPragma;
    @XmlElement(name = "atomic_components_pragma")
    protected Object atomicComponentsPragma;
    @XmlElement(name = "attach_handler_pragma")
    protected Object attachHandlerPragma;
    @XmlElement(name = "controlled_pragma")
    protected Object controlledPragma;
    @XmlElement(name = "convention_pragma")
    protected Object conventionPragma;
    @XmlElement(name = "discard_names_pragma")
    protected Object discardNamesPragma;
    @XmlElement(name = "elaborate_pragma")
    protected Object elaboratePragma;
    @XmlElement(name = "elaborate_all_pragma")
    protected Object elaborateAllPragma;
    @XmlElement(name = "elaborate_body_pragma")
    protected Object elaborateBodyPragma;
    @XmlElement(name = "export_pragma")
    protected Object exportPragma;
    @XmlElement(name = "import_pragma")
    protected Object importPragma;
    @XmlElement(name = "inline_pragma")
    protected Object inlinePragma;
    @XmlElement(name = "inspection_point_pragma")
    protected Object inspectionPointPragma;
    @XmlElement(name = "interrupt_handler_pragma")
    protected Object interruptHandlerPragma;
    @XmlElement(name = "interrupt_priority_pragma")
    protected Object interruptPriorityPragma;
    @XmlElement(name = "linker_options_pragma")
    protected Object linkerOptionsPragma;
    @XmlElement(name = "list_pragma")
    protected Object listPragma;
    @XmlElement(name = "locking_policy_pragma")
    protected Object lockingPolicyPragma;
    @XmlElement(name = "normalize_scalars_pragma")
    protected Object normalizeScalarsPragma;
    @XmlElement(name = "optimize_pragma")
    protected Object optimizePragma;
    @XmlElement(name = "pack_pragma")
    protected Object packPragma;
    @XmlElement(name = "page_pragma")
    protected Object pagePragma;
    @XmlElement(name = "preelaborate_pragma")
    protected Object preelaboratePragma;
    @XmlElement(name = "priority_pragma")
    protected Object priorityPragma;
    @XmlElement(name = "pure_pragma")
    protected Object purePragma;
    @XmlElement(name = "queuing_policy_pragma")
    protected Object queuingPolicyPragma;
    @XmlElement(name = "remote_call_interface_pragma")
    protected Object remoteCallInterfacePragma;
    @XmlElement(name = "remote_types_pragma")
    protected Object remoteTypesPragma;
    @XmlElement(name = "restrictions_pragma")
    protected Object restrictionsPragma;
    @XmlElement(name = "reviewable_pragma")
    protected Object reviewablePragma;
    @XmlElement(name = "shared_passive_pragma")
    protected Object sharedPassivePragma;
    @XmlElement(name = "storage_size_pragma")
    protected Object storageSizePragma;
    @XmlElement(name = "suppress_pragma")
    protected Object suppressPragma;
    @XmlElement(name = "task_dispatching_policy_pragma")
    protected Object taskDispatchingPolicyPragma;
    @XmlElement(name = "volatile_pragma")
    protected Object volatilePragma;
    @XmlElement(name = "volatile_components_pragma")
    protected Object volatileComponentsPragma;
    @XmlElement(name = "assert_pragma")
    protected Object assertPragma;
    @XmlElement(name = "assertion_policy_pragma")
    protected Object assertionPolicyPragma;
    @XmlElement(name = "detect_blocking_pragma")
    protected Object detectBlockingPragma;
    @XmlElement(name = "no_return_pragma")
    protected Object noReturnPragma;
    @XmlElement(name = "partition_elaboration_policy_pragma")
    protected Object partitionElaborationPolicyPragma;
    @XmlElement(name = "preelaborable_initialization_pragma")
    protected Object preelaborableInitializationPragma;
    @XmlElement(name = "priority_specific_dispatching_pragma")
    protected Object prioritySpecificDispatchingPragma;
    @XmlElement(name = "profile_pragma")
    protected Object profilePragma;
    @XmlElement(name = "relative_deadline_pragma")
    protected Object relativeDeadlinePragma;
    @XmlElement(name = "unchecked_union_pragma")
    protected Object uncheckedUnionPragma;
    @XmlElement(name = "unsuppress_pragma")
    protected Object unsuppressPragma;
    @XmlElement(name = "default_storage_pool_pragma")
    protected Object defaultStoragePoolPragma;
    @XmlElement(name = "dispatching_domain_pragma")
    protected Object dispatchingDomainPragma;
    @XmlElement(name = "cpu_pragma")
    protected Object cpuPragma;
    @XmlElement(name = "independent_pragma")
    protected Object independentPragma;
    @XmlElement(name = "independent_components_pragma")
    protected Object independentComponentsPragma;
    @XmlElement(name = "implementation_defined_pragma")
    protected Object implementationDefinedPragma;
    @XmlElement(name = "unknown_pragma")
    protected Object unknownPragma;

    /**
     * Gets the value of the notAnElement property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getNotAnElement() {
        return notAnElement;
    }

    /**
     * Sets the value of the notAnElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setNotAnElement(Object value) {
        this.notAnElement = value;
    }

    /**
     * Gets the value of the ifPath property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getIfPath() {
        return ifPath;
    }

    /**
     * Sets the value of the ifPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setIfPath(Object value) {
        this.ifPath = value;
    }

    /**
     * Gets the value of the elsifPath property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getElsifPath() {
        return elsifPath;
    }

    /**
     * Sets the value of the elsifPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setElsifPath(Object value) {
        this.elsifPath = value;
    }

    /**
     * Gets the value of the elsePath property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getElsePath() {
        return elsePath;
    }

    /**
     * Sets the value of the elsePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setElsePath(Object value) {
        this.elsePath = value;
    }

    /**
     * Gets the value of the casePath property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getCasePath() {
        return casePath;
    }

    /**
     * Sets the value of the casePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setCasePath(Object value) {
        this.casePath = value;
    }

    /**
     * Gets the value of the selectPath property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getSelectPath() {
        return selectPath;
    }

    /**
     * Sets the value of the selectPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setSelectPath(Object value) {
        this.selectPath = value;
    }

    /**
     * Gets the value of the orPath property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getOrPath() {
        return orPath;
    }

    /**
     * Sets the value of the orPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setOrPath(Object value) {
        this.orPath = value;
    }

    /**
     * Gets the value of the thenAbortPath property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getThenAbortPath() {
        return thenAbortPath;
    }

    /**
     * Sets the value of the thenAbortPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setThenAbortPath(Object value) {
        this.thenAbortPath = value;
    }

    /**
     * Gets the value of the caseExpressionPath property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getCaseExpressionPath() {
        return caseExpressionPath;
    }

    /**
     * Sets the value of the caseExpressionPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setCaseExpressionPath(Object value) {
        this.caseExpressionPath = value;
    }

    /**
     * Gets the value of the ifExpressionPath property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getIfExpressionPath() {
        return ifExpressionPath;
    }

    /**
     * Sets the value of the ifExpressionPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setIfExpressionPath(Object value) {
        this.ifExpressionPath = value;
    }

    /**
     * Gets the value of the elsifExpressionPath property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getElsifExpressionPath() {
        return elsifExpressionPath;
    }

    /**
     * Sets the value of the elsifExpressionPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setElsifExpressionPath(Object value) {
        this.elsifExpressionPath = value;
    }

    /**
     * Gets the value of the elseExpressionPath property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getElseExpressionPath() {
        return elseExpressionPath;
    }

    /**
     * Sets the value of the elseExpressionPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setElseExpressionPath(Object value) {
        this.elseExpressionPath = value;
    }

    /**
     * Gets the value of the allCallsRemotePragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAllCallsRemotePragma() {
        return allCallsRemotePragma;
    }

    /**
     * Sets the value of the allCallsRemotePragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAllCallsRemotePragma(Object value) {
        this.allCallsRemotePragma = value;
    }

    /**
     * Gets the value of the asynchronousPragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAsynchronousPragma() {
        return asynchronousPragma;
    }

    /**
     * Sets the value of the asynchronousPragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAsynchronousPragma(Object value) {
        this.asynchronousPragma = value;
    }

    /**
     * Gets the value of the atomicPragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAtomicPragma() {
        return atomicPragma;
    }

    /**
     * Sets the value of the atomicPragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAtomicPragma(Object value) {
        this.atomicPragma = value;
    }

    /**
     * Gets the value of the atomicComponentsPragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAtomicComponentsPragma() {
        return atomicComponentsPragma;
    }

    /**
     * Sets the value of the atomicComponentsPragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAtomicComponentsPragma(Object value) {
        this.atomicComponentsPragma = value;
    }

    /**
     * Gets the value of the attachHandlerPragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAttachHandlerPragma() {
        return attachHandlerPragma;
    }

    /**
     * Sets the value of the attachHandlerPragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAttachHandlerPragma(Object value) {
        this.attachHandlerPragma = value;
    }

    /**
     * Gets the value of the controlledPragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getControlledPragma() {
        return controlledPragma;
    }

    /**
     * Sets the value of the controlledPragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setControlledPragma(Object value) {
        this.controlledPragma = value;
    }

    /**
     * Gets the value of the conventionPragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getConventionPragma() {
        return conventionPragma;
    }

    /**
     * Sets the value of the conventionPragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setConventionPragma(Object value) {
        this.conventionPragma = value;
    }

    /**
     * Gets the value of the discardNamesPragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDiscardNamesPragma() {
        return discardNamesPragma;
    }

    /**
     * Sets the value of the discardNamesPragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDiscardNamesPragma(Object value) {
        this.discardNamesPragma = value;
    }

    /**
     * Gets the value of the elaboratePragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getElaboratePragma() {
        return elaboratePragma;
    }

    /**
     * Sets the value of the elaboratePragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setElaboratePragma(Object value) {
        this.elaboratePragma = value;
    }

    /**
     * Gets the value of the elaborateAllPragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getElaborateAllPragma() {
        return elaborateAllPragma;
    }

    /**
     * Sets the value of the elaborateAllPragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setElaborateAllPragma(Object value) {
        this.elaborateAllPragma = value;
    }

    /**
     * Gets the value of the elaborateBodyPragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getElaborateBodyPragma() {
        return elaborateBodyPragma;
    }

    /**
     * Sets the value of the elaborateBodyPragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setElaborateBodyPragma(Object value) {
        this.elaborateBodyPragma = value;
    }

    /**
     * Gets the value of the exportPragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getExportPragma() {
        return exportPragma;
    }

    /**
     * Sets the value of the exportPragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setExportPragma(Object value) {
        this.exportPragma = value;
    }

    /**
     * Gets the value of the importPragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getImportPragma() {
        return importPragma;
    }

    /**
     * Sets the value of the importPragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setImportPragma(Object value) {
        this.importPragma = value;
    }

    /**
     * Gets the value of the inlinePragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getInlinePragma() {
        return inlinePragma;
    }

    /**
     * Sets the value of the inlinePragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setInlinePragma(Object value) {
        this.inlinePragma = value;
    }

    /**
     * Gets the value of the inspectionPointPragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getInspectionPointPragma() {
        return inspectionPointPragma;
    }

    /**
     * Sets the value of the inspectionPointPragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setInspectionPointPragma(Object value) {
        this.inspectionPointPragma = value;
    }

    /**
     * Gets the value of the interruptHandlerPragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getInterruptHandlerPragma() {
        return interruptHandlerPragma;
    }

    /**
     * Sets the value of the interruptHandlerPragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setInterruptHandlerPragma(Object value) {
        this.interruptHandlerPragma = value;
    }

    /**
     * Gets the value of the interruptPriorityPragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getInterruptPriorityPragma() {
        return interruptPriorityPragma;
    }

    /**
     * Sets the value of the interruptPriorityPragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setInterruptPriorityPragma(Object value) {
        this.interruptPriorityPragma = value;
    }

    /**
     * Gets the value of the linkerOptionsPragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getLinkerOptionsPragma() {
        return linkerOptionsPragma;
    }

    /**
     * Sets the value of the linkerOptionsPragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setLinkerOptionsPragma(Object value) {
        this.linkerOptionsPragma = value;
    }

    /**
     * Gets the value of the listPragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getListPragma() {
        return listPragma;
    }

    /**
     * Sets the value of the listPragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setListPragma(Object value) {
        this.listPragma = value;
    }

    /**
     * Gets the value of the lockingPolicyPragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getLockingPolicyPragma() {
        return lockingPolicyPragma;
    }

    /**
     * Sets the value of the lockingPolicyPragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setLockingPolicyPragma(Object value) {
        this.lockingPolicyPragma = value;
    }

    /**
     * Gets the value of the normalizeScalarsPragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getNormalizeScalarsPragma() {
        return normalizeScalarsPragma;
    }

    /**
     * Sets the value of the normalizeScalarsPragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setNormalizeScalarsPragma(Object value) {
        this.normalizeScalarsPragma = value;
    }

    /**
     * Gets the value of the optimizePragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getOptimizePragma() {
        return optimizePragma;
    }

    /**
     * Sets the value of the optimizePragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setOptimizePragma(Object value) {
        this.optimizePragma = value;
    }

    /**
     * Gets the value of the packPragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPackPragma() {
        return packPragma;
    }

    /**
     * Sets the value of the packPragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPackPragma(Object value) {
        this.packPragma = value;
    }

    /**
     * Gets the value of the pagePragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPagePragma() {
        return pagePragma;
    }

    /**
     * Sets the value of the pagePragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPagePragma(Object value) {
        this.pagePragma = value;
    }

    /**
     * Gets the value of the preelaboratePragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPreelaboratePragma() {
        return preelaboratePragma;
    }

    /**
     * Sets the value of the preelaboratePragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPreelaboratePragma(Object value) {
        this.preelaboratePragma = value;
    }

    /**
     * Gets the value of the priorityPragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPriorityPragma() {
        return priorityPragma;
    }

    /**
     * Sets the value of the priorityPragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPriorityPragma(Object value) {
        this.priorityPragma = value;
    }

    /**
     * Gets the value of the purePragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPurePragma() {
        return purePragma;
    }

    /**
     * Sets the value of the purePragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPurePragma(Object value) {
        this.purePragma = value;
    }

    /**
     * Gets the value of the queuingPolicyPragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getQueuingPolicyPragma() {
        return queuingPolicyPragma;
    }

    /**
     * Sets the value of the queuingPolicyPragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setQueuingPolicyPragma(Object value) {
        this.queuingPolicyPragma = value;
    }

    /**
     * Gets the value of the remoteCallInterfacePragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getRemoteCallInterfacePragma() {
        return remoteCallInterfacePragma;
    }

    /**
     * Sets the value of the remoteCallInterfacePragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setRemoteCallInterfacePragma(Object value) {
        this.remoteCallInterfacePragma = value;
    }

    /**
     * Gets the value of the remoteTypesPragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getRemoteTypesPragma() {
        return remoteTypesPragma;
    }

    /**
     * Sets the value of the remoteTypesPragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setRemoteTypesPragma(Object value) {
        this.remoteTypesPragma = value;
    }

    /**
     * Gets the value of the restrictionsPragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getRestrictionsPragma() {
        return restrictionsPragma;
    }

    /**
     * Sets the value of the restrictionsPragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setRestrictionsPragma(Object value) {
        this.restrictionsPragma = value;
    }

    /**
     * Gets the value of the reviewablePragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getReviewablePragma() {
        return reviewablePragma;
    }

    /**
     * Sets the value of the reviewablePragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setReviewablePragma(Object value) {
        this.reviewablePragma = value;
    }

    /**
     * Gets the value of the sharedPassivePragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getSharedPassivePragma() {
        return sharedPassivePragma;
    }

    /**
     * Sets the value of the sharedPassivePragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setSharedPassivePragma(Object value) {
        this.sharedPassivePragma = value;
    }

    /**
     * Gets the value of the storageSizePragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getStorageSizePragma() {
        return storageSizePragma;
    }

    /**
     * Sets the value of the storageSizePragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setStorageSizePragma(Object value) {
        this.storageSizePragma = value;
    }

    /**
     * Gets the value of the suppressPragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getSuppressPragma() {
        return suppressPragma;
    }

    /**
     * Sets the value of the suppressPragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setSuppressPragma(Object value) {
        this.suppressPragma = value;
    }

    /**
     * Gets the value of the taskDispatchingPolicyPragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getTaskDispatchingPolicyPragma() {
        return taskDispatchingPolicyPragma;
    }

    /**
     * Sets the value of the taskDispatchingPolicyPragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setTaskDispatchingPolicyPragma(Object value) {
        this.taskDispatchingPolicyPragma = value;
    }

    /**
     * Gets the value of the volatilePragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getVolatilePragma() {
        return volatilePragma;
    }

    /**
     * Sets the value of the volatilePragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setVolatilePragma(Object value) {
        this.volatilePragma = value;
    }

    /**
     * Gets the value of the volatileComponentsPragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getVolatileComponentsPragma() {
        return volatileComponentsPragma;
    }

    /**
     * Sets the value of the volatileComponentsPragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setVolatileComponentsPragma(Object value) {
        this.volatileComponentsPragma = value;
    }

    /**
     * Gets the value of the assertPragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAssertPragma() {
        return assertPragma;
    }

    /**
     * Sets the value of the assertPragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAssertPragma(Object value) {
        this.assertPragma = value;
    }

    /**
     * Gets the value of the assertionPolicyPragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAssertionPolicyPragma() {
        return assertionPolicyPragma;
    }

    /**
     * Sets the value of the assertionPolicyPragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAssertionPolicyPragma(Object value) {
        this.assertionPolicyPragma = value;
    }

    /**
     * Gets the value of the detectBlockingPragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDetectBlockingPragma() {
        return detectBlockingPragma;
    }

    /**
     * Sets the value of the detectBlockingPragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDetectBlockingPragma(Object value) {
        this.detectBlockingPragma = value;
    }

    /**
     * Gets the value of the noReturnPragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getNoReturnPragma() {
        return noReturnPragma;
    }

    /**
     * Sets the value of the noReturnPragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setNoReturnPragma(Object value) {
        this.noReturnPragma = value;
    }

    /**
     * Gets the value of the partitionElaborationPolicyPragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPartitionElaborationPolicyPragma() {
        return partitionElaborationPolicyPragma;
    }

    /**
     * Sets the value of the partitionElaborationPolicyPragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPartitionElaborationPolicyPragma(Object value) {
        this.partitionElaborationPolicyPragma = value;
    }

    /**
     * Gets the value of the preelaborableInitializationPragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPreelaborableInitializationPragma() {
        return preelaborableInitializationPragma;
    }

    /**
     * Sets the value of the preelaborableInitializationPragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPreelaborableInitializationPragma(Object value) {
        this.preelaborableInitializationPragma = value;
    }

    /**
     * Gets the value of the prioritySpecificDispatchingPragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPrioritySpecificDispatchingPragma() {
        return prioritySpecificDispatchingPragma;
    }

    /**
     * Sets the value of the prioritySpecificDispatchingPragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPrioritySpecificDispatchingPragma(Object value) {
        this.prioritySpecificDispatchingPragma = value;
    }

    /**
     * Gets the value of the profilePragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getProfilePragma() {
        return profilePragma;
    }

    /**
     * Sets the value of the profilePragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setProfilePragma(Object value) {
        this.profilePragma = value;
    }

    /**
     * Gets the value of the relativeDeadlinePragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getRelativeDeadlinePragma() {
        return relativeDeadlinePragma;
    }

    /**
     * Sets the value of the relativeDeadlinePragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setRelativeDeadlinePragma(Object value) {
        this.relativeDeadlinePragma = value;
    }

    /**
     * Gets the value of the uncheckedUnionPragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getUncheckedUnionPragma() {
        return uncheckedUnionPragma;
    }

    /**
     * Sets the value of the uncheckedUnionPragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setUncheckedUnionPragma(Object value) {
        this.uncheckedUnionPragma = value;
    }

    /**
     * Gets the value of the unsuppressPragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getUnsuppressPragma() {
        return unsuppressPragma;
    }

    /**
     * Sets the value of the unsuppressPragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setUnsuppressPragma(Object value) {
        this.unsuppressPragma = value;
    }

    /**
     * Gets the value of the defaultStoragePoolPragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDefaultStoragePoolPragma() {
        return defaultStoragePoolPragma;
    }

    /**
     * Sets the value of the defaultStoragePoolPragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDefaultStoragePoolPragma(Object value) {
        this.defaultStoragePoolPragma = value;
    }

    /**
     * Gets the value of the dispatchingDomainPragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDispatchingDomainPragma() {
        return dispatchingDomainPragma;
    }

    /**
     * Sets the value of the dispatchingDomainPragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDispatchingDomainPragma(Object value) {
        this.dispatchingDomainPragma = value;
    }

    /**
     * Gets the value of the cpuPragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getCpuPragma() {
        return cpuPragma;
    }

    /**
     * Sets the value of the cpuPragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setCpuPragma(Object value) {
        this.cpuPragma = value;
    }

    /**
     * Gets the value of the independentPragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getIndependentPragma() {
        return independentPragma;
    }

    /**
     * Sets the value of the independentPragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setIndependentPragma(Object value) {
        this.independentPragma = value;
    }

    /**
     * Gets the value of the independentComponentsPragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getIndependentComponentsPragma() {
        return independentComponentsPragma;
    }

    /**
     * Sets the value of the independentComponentsPragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setIndependentComponentsPragma(Object value) {
        this.independentComponentsPragma = value;
    }

    /**
     * Gets the value of the implementationDefinedPragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getImplementationDefinedPragma() {
        return implementationDefinedPragma;
    }

    /**
     * Sets the value of the implementationDefinedPragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setImplementationDefinedPragma(Object value) {
        this.implementationDefinedPragma = value;
    }

    /**
     * Gets the value of the unknownPragma property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getUnknownPragma() {
        return unknownPragma;
    }

    /**
     * Sets the value of the unknownPragma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setUnknownPragma(Object value) {
        this.unknownPragma = value;
    }

}
