//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//

package org.sireum.bakar.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Component_Definition complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Component_Definition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sloc" type="{}Source_Location"/>
 *         &lt;element name="has_aliased_q">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="aliased" type="{}Aliased"/>
 *                   &lt;element name="not_an_element" type="{}Not_An_Element"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="component_definition_view_q" type="{}Definition_Class"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Component_Definition", propOrder = { "sloc", "hasAliasedQ",
    "componentDefinitionViewQ" })
public class ComponentDefinition {

  /**
   * <p>
   * Java class for anonymous complex type.
   * 
   * <p>
   * The following schema fragment specifies the expected content contained
   * within this class.
   * 
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;choice>
   *         &lt;element name="aliased" type="{}Aliased"/>
   *         &lt;element name="not_an_element" type="{}Not_An_Element"/>
   *       &lt;/choice>
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = { "aliased", "notAnElement" })
  public static class HasAliasedQ {

    protected Aliased aliased;
    @XmlElement(name = "not_an_element")
    protected NotAnElement notAnElement;

    /**
     * Gets the value of the aliased property.
     * 
     * @return possible object is {@link Aliased }
     * 
     */
    public Aliased getAliased() {
      return this.aliased;
    }

    /**
     * Gets the value of the notAnElement property.
     * 
     * @return possible object is {@link NotAnElement }
     * 
     */
    public NotAnElement getNotAnElement() {
      return this.notAnElement;
    }

    /**
     * Sets the value of the aliased property.
     * 
     * @param value
     *          allowed object is {@link Aliased }
     * 
     */
    public void setAliased(final Aliased value) {
      this.aliased = value;
    }

    /**
     * Sets the value of the notAnElement property.
     * 
     * @param value
     *          allowed object is {@link NotAnElement }
     * 
     */
    public void setNotAnElement(final NotAnElement value) {
      this.notAnElement = value;
    }

  }

  @XmlElement(required = true)
  protected SourceLocation sloc;
  @XmlElement(name = "has_aliased_q", required = true)
  protected ComponentDefinition.HasAliasedQ hasAliasedQ;

  @XmlElement(name = "component_definition_view_q", required = true)
  protected DefinitionClass componentDefinitionViewQ;

  /**
   * Gets the value of the componentDefinitionViewQ property.
   * 
   * @return possible object is {@link DefinitionClass }
   * 
   */
  public DefinitionClass getComponentDefinitionViewQ() {
    return this.componentDefinitionViewQ;
  }

  /**
   * Gets the value of the hasAliasedQ property.
   * 
   * @return possible object is {@link ComponentDefinition.HasAliasedQ }
   * 
   */
  public ComponentDefinition.HasAliasedQ getHasAliasedQ() {
    return this.hasAliasedQ;
  }

  /**
   * Gets the value of the sloc property.
   * 
   * @return possible object is {@link SourceLocation }
   * 
   */
  public SourceLocation getSloc() {
    return this.sloc;
  }

  /**
   * Sets the value of the componentDefinitionViewQ property.
   * 
   * @param value
   *          allowed object is {@link DefinitionClass }
   * 
   */
  public void setComponentDefinitionViewQ(final DefinitionClass value) {
    this.componentDefinitionViewQ = value;
  }

  /**
   * Sets the value of the hasAliasedQ property.
   * 
   * @param value
   *          allowed object is {@link ComponentDefinition.HasAliasedQ }
   * 
   */
  public void setHasAliasedQ(final ComponentDefinition.HasAliasedQ value) {
    this.hasAliasedQ = value;
  }

  /**
   * Sets the value of the sloc property.
   * 
   * @param value
   *          allowed object is {@link SourceLocation }
   * 
   */
  public void setSloc(final SourceLocation value) {
    this.sloc = value;
  }

}
