// Do not edit this file. It is auto-generated from org.sireum.core.module.ChunkingPilarParserV2
// by org.sireum.pipeline.gen.ModuleGenerator

package org.sireum.core.module

import org.sireum.util._
import org.sireum.pipeline._
import org.sireum.pilar.ast.Model
import scala.collection.immutable.Seq

object ChunkingPilarParserV2Module extends PipelineModule {
  def title = "Chunking Pilar Parser v2"
  def origin = classOf[ChunkingPilarParserV2]

  val sourcesKey = "ChunkingPilarParserV2.sources"
  val globalModelsKey = "Global.models"
  val modelsKey = "ChunkingPilarParserV2.models"
  val globalSourcesKey = "Global.sources"

  def compute(job : PipelineJob, info : PipelineJobModuleInfo) : MBuffer[Tag] = {
    val tags = marrayEmpty[Tag]
    try {
      val module = Class.forName("org.sireum.core.module.ChunkingPilarParserV2ModuleDef")
      val cons = module.getConstructors()(0)
      val params = Array[AnyRef](job, info)
      val inst = cons.newInstance(params : _*)
    } catch {
      case e : Throwable =>
        e.printStackTrace
        tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker, e.getMessage);
    }
    return tags
  }

  override def initialize(job : PipelineJob) {
  }

  override def validPipeline(stage : PipelineStage, job : PipelineJob) : MBuffer[Tag] = {
    val tags = marrayEmpty[Tag]
    val deps = ilist[PipelineModule](PilarSourcesModule)
    deps.foreach(d =>
      if (stage.modules.contains(d)) {
        tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
          "'" + this.title + "' depends on '" + d.title + "' yet both were found in stage '" + stage.title + "'"
        )
      }
    )
    return tags
  }

  def inputDefined(job : PipelineJob) : MBuffer[Tag] = {
    val tags = marrayEmpty[Tag]
    var _sources : scala.Option[AnyRef] = None
    var _sourcesKey : scala.Option[String] = None

    val keylistsources = List(ChunkingPilarParserV2Module.globalSourcesKey, PilarSourcesModule.sourcesKey)
    keylistsources.foreach(key =>
      if (job ? key) {
        if (_sources.isEmpty) {
          _sources = Some(job(key))
          _sourcesKey = Some(key)
        }
        if (!(job(key).asInstanceOf[AnyRef] eq _sources.get)) {
          tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "Input error for '" + this.title + "': 'sources' keys '" + _sourcesKey.get + " and '" + key + "' point to different objects.")
        }
      }
    )

    _sources match {
      case Some(x) =>
        if (!x.isInstanceOf[scala.collection.immutable.Seq[scala.util.Either[java.lang.String, java.lang.String]]]) {
          tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
            "Input error for '" + this.title + "': Wrong type found for 'sources'.  Expecting 'scala.collection.immutable.Seq[scala.util.Either[java.lang.String, java.lang.String]]' but found '" + x.getClass.toString + "'")
        }
      case None =>
        tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
          "Input error for '" + this.title + "': No value found for 'sources'")
    }
    return tags
  }

  def outputDefined(job : PipelineJob) : MBuffer[Tag] = {
    val tags = marrayEmpty[Tag]
    if (!(job ? ChunkingPilarParserV2Module.modelsKey) && !(job ? ChunkingPilarParserV2Module.globalModelsKey)) {
      tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
        "Output error for '" + this.title + "': No entry found for 'models'. Expecting (ChunkingPilarParserV2Module.modelsKey or ChunkingPilarParserV2Module.globalModelsKey)")
    }

    if (job ? ChunkingPilarParserV2Module.modelsKey && !job(ChunkingPilarParserV2Module.modelsKey).isInstanceOf[scala.collection.immutable.Seq[org.sireum.pilar.ast.Model]]) {
      tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
        "Output error for '" + this.title + "': Wrong type found for ChunkingPilarParserV2Module.modelsKey.  Expecting 'scala.collection.immutable.Seq[org.sireum.pilar.ast.Model]' but found '" +
          job(ChunkingPilarParserV2Module.modelsKey).getClass.toString + "'")
    }

    if (job ? ChunkingPilarParserV2Module.globalModelsKey && !job(ChunkingPilarParserV2Module.globalModelsKey).isInstanceOf[scala.collection.immutable.Seq[org.sireum.pilar.ast.Model]]) {
      tags += PipelineUtil.genTag(PipelineUtil.ErrorMarker,
        "Output error for '" + this.title + "': Wrong type found for ChunkingPilarParserV2Module.globalModelsKey.  Expecting 'scala.collection.immutable.Seq[org.sireum.pilar.ast.Model]' but found '" +
          job(ChunkingPilarParserV2Module.globalModelsKey).getClass.toString + "'")
    }
    return tags
  }

  def getSources(options : scala.collection.Map[Property.Key, Any]) : scala.collection.immutable.Seq[scala.util.Either[java.lang.String, java.lang.String]] = {
    if (options.contains(ChunkingPilarParserV2Module.globalSourcesKey)) {
      return options(ChunkingPilarParserV2Module.globalSourcesKey).asInstanceOf[scala.collection.immutable.Seq[scala.util.Either[java.lang.String, java.lang.String]]]
    }
    if (options.contains(ChunkingPilarParserV2Module.sourcesKey)) {
      return options(ChunkingPilarParserV2Module.sourcesKey).asInstanceOf[scala.collection.immutable.Seq[scala.util.Either[java.lang.String, java.lang.String]]]
    }
    if (options.contains(PilarSourcesModule.sourcesKey)) {
      return options(PilarSourcesModule.sourcesKey).asInstanceOf[scala.collection.immutable.Seq[scala.util.Either[java.lang.String, java.lang.String]]]
    }

    throw new Exception("Pipeline checker should guarantee we never reach here")
  }

  def setSources(options : MMap[Property.Key, Any], sources : scala.collection.immutable.Seq[scala.util.Either[java.lang.String, java.lang.String]]) : MMap[Property.Key, Any] = {

    options(ChunkingPilarParserV2Module.globalSourcesKey) = sources
    options(sourcesKey) = sources

    return options
  }

  def getModels(options : scala.collection.Map[Property.Key, Any]) : scala.collection.immutable.Seq[org.sireum.pilar.ast.Model] = {
    if (options.contains(ChunkingPilarParserV2Module.globalModelsKey)) {
      return options(ChunkingPilarParserV2Module.globalModelsKey).asInstanceOf[scala.collection.immutable.Seq[org.sireum.pilar.ast.Model]]
    }
    if (options.contains(ChunkingPilarParserV2Module.modelsKey)) {
      return options(ChunkingPilarParserV2Module.modelsKey).asInstanceOf[scala.collection.immutable.Seq[org.sireum.pilar.ast.Model]]
    }

    throw new Exception("Pipeline checker should guarantee we never reach here")
  }

  def setModels(options : MMap[Property.Key, Any], models : scala.collection.immutable.Seq[org.sireum.pilar.ast.Model]) : MMap[Property.Key, Any] = {

    options(ChunkingPilarParserV2Module.globalModelsKey) = models
    options(modelsKey) = models

    return options
  }

  object ConsumerView {
    implicit class ChunkingPilarParserV2ModuleConsumerView(val job : PropertyProvider) extends AnyVal {
      def sources : scala.collection.immutable.Seq[scala.util.Either[java.lang.String, java.lang.String]] = ChunkingPilarParserV2Module.getSources(job.propertyMap)
      def models : scala.collection.immutable.Seq[org.sireum.pilar.ast.Model] = ChunkingPilarParserV2Module.getModels(job.propertyMap)
    }
  }

  object ProducerView {
    implicit class ChunkingPilarParserV2ModuleProducerView(val job : PropertyProvider) extends AnyVal {

      def sources_=(sources : scala.collection.immutable.Seq[scala.util.Either[java.lang.String, java.lang.String]]) { ChunkingPilarParserV2Module.setSources(job.propertyMap, sources) }
      def sources : scala.collection.immutable.Seq[scala.util.Either[java.lang.String, java.lang.String]] = ChunkingPilarParserV2Module.getSources(job.propertyMap)

      def models_=(models : scala.collection.immutable.Seq[org.sireum.pilar.ast.Model]) { ChunkingPilarParserV2Module.setModels(job.propertyMap, models) }
      def models : scala.collection.immutable.Seq[org.sireum.pilar.ast.Model] = ChunkingPilarParserV2Module.getModels(job.propertyMap)
    }
  }
}

trait ChunkingPilarParserV2Module {
  def job : PipelineJob

  def sources : scala.collection.immutable.Seq[scala.util.Either[java.lang.String, java.lang.String]] = ChunkingPilarParserV2Module.getSources(job.propertyMap)

  def models_=(models : scala.collection.immutable.Seq[org.sireum.pilar.ast.Model]) { ChunkingPilarParserV2Module.setModels(job.propertyMap, models) }
  def models : scala.collection.immutable.Seq[org.sireum.pilar.ast.Model] = ChunkingPilarParserV2Module.getModels(job.propertyMap)
}